[package]
name = "stm32f469i-disco"
version = "0.1.0"
authors = ["xd009642 <danielmckenna93@gmail.com>"]

[dependencies]
cortex-m = "0.4.3"
stm32f469xx = "0.1.0"
stm32f469xx-hal = { git = "https://github.com/xd009642/stm32f469xx-hal" }
embedded-hal = "0.1.2"
nb = "0.1.1"
